spring.application.name=SpringBootTrial01

# DB?????????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# SQL???????
spring.sql.init.mode=never

# JPA?????????????????????
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

trial03.aaa=aaa
trial03.bbb=bbb
